---
title: "Untitled"
author: "Xiangxiong Feng"
date: "2023-10-14"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)

library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



# Problem 1

```{r}

data("instacart")
instacart = 
  instacart |> 
  as_tibble()
```

```{r}
instacart |> 
  count(aisle) |> 
  arrange(desc(n))
```

```{r}
instacart |> 
  count(aisle) |> 
  filter(n > 10000) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  ggplot(aes(x = aisle, y = n)) + 
  geom_point() + 
  labs(title = "Number of items ordered in each aisle") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```
```{r}
instacart |> 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) |>
  group_by(aisle) |> 
  count(product_name) |> 
  mutate(rank = min_rank(desc(n))) |> 
  filter(rank < 4) |> 
  arrange(desc(n)) |>
  knitr::kable()
```


```{r}

instacart |>
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) |>
  group_by(product_name, order_dow) |>
  summarize(mean_hour = mean(order_hour_of_day)) |>
  pivot_wider(
    names_from = order_dow, 
    values_from = mean_hour) |>
  knitr::kable(digits = 2)
```





# Problem 2

```{r}
data("brfss_smart2010")


```

# data cleaning 
```{r}

brfss_smart2010 =
  brfss_smart2010 |>
  janitor::clean_names() |>
  filter(topic == 'Overall Health',
         response %in% c('Excellent', "Very good", "Good", "Fair", "Poor")) |>
  mutate(response = factor(response, 
                           levels = c("Poor", "Fair", "Good",
                                                "Very good","Excellent"), 
                           ordered = TRUE))
```

# Question 1 
```{r}
#count which states were observed at 7 or more locations in 2002
brfss_smart2010_2002 = 
  brfss_smart2010 |>
  filter(year==2002)|>
  group_by(locationabbr, locationdesc)|>
  summarize(n_obs = n())|>
  count(locationabbr)|>
  filter(n>=7) 
Morethanseven_2002 = as.list(brfss_smart2010_2002$locationabbr)

#count which states were observed at 7 or more locations in 2002
brfss_smart2010_2010 = 
  brfss_smart2010 |>
  filter(year==2010)|>
  group_by(locationabbr, locationdesc)|>
  summarize(n_obs = n())|>
  count(locationabbr)|>
  filter(n>=7) 
Morethanseven_2010 = as.list(brfss_smart2010_2010$locationabbr)

```

In 2002, `r Morethanseven_2002` were observed at 7 or more locations. In 2010, `r Morethanseven_2010`were observed at 7 or more locations.















